quick/history/urls.py
from django.urls import path

from . import views

app_name="history"

urlpatterns = [
  path('', views.index, name='index'),
  path('<int:id>/', views.details, name='details'),
  path('newArtist', views.newArtist, name='newArtist'),
  path('newSong', views.newSong, name='newSong'),
  path('deleteSong', views.deleteSong, name='deleteSong')

]

quick/quick/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('history/', include('history.urls'))
]

quick/history/models.py
from django.db import models

class Artist(models.Model):
    artist_name = models.CharField(max_length=200)

    def __str__(self):
      return self.artist_name



class Song(models.Model):
    song_name = models.CharField(max_length=200)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)


    def __str__(self):
      return self.song_name



# join table with artist and song
# add albums

quick/history/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Artist, Song


def index(request):
    artist_list = Artist.objects.all()
    context = {'artist_list': artist_list}
    return render(request, 'history/index.html', context)
    # return HttpResponse(f"We made it!")

def details(request, id):
  # print("LOOK HERE", request.POST['artist'])
  song_list = Song.objects.filter(artist_id = id)
  artist = Artist.objects.get(pk=id)
  context = {'song_list': song_list, 'artist': artist}
  return render(request, 'history/details.html', context)


def newArtist(request):

  artist = Artist(artist_name = request.POST['artist'])
  artist.save()
  added_artist = Artist.objects.filter(artist_name = request.POST['artist'])

  print("added artist", str(added_artist[0].id))
  # args=([value],) must be a tupple
  return HttpResponseRedirect(reverse('history:details', args=(added_artist[0].id,)))


def newSong(request):
  artistId = Artist.objects.get(artist_name=request.POST['artist'])
  print("artistId", artistId.id)
  song = Song(song_name = request.POST['song'], artist_id=artistId.id)
  song.save()
  return HttpResponseRedirect(reverse('history:details', args=(artistId.id, )))
  # print("SONG", song)

def deleteSong(request, songId):
  print(songId)

quick/history/templates/history/details.html
<h1>{{ artist.artist_name }}</h1>
{% if song_list %}
<ul>
  {% for song in song_list %}
  <li>{{ song.song_name }}</li>
  <a href="{% url 'history:deleteSong' '{{song.id}}'' %}">Delete</a>
  {% endfor %}
{% else %}
  <p>No Songs</p>

</ul>
{% endif %}
<br>
<br>
<form method="post" action="{% url 'history:newSong' %}">
  {% csrf_token %}
  <label for="newSong">New Song</label><br>
  <input type="text" name="song" id = "newSong"><br><br>
  <input type="hidden" name="artist" value = "{{artist.artist_name}}" id = "artist">
  <input type = "submit" value="Add Song">
</form>


quick/history/templates/history/index.html
{% if artist_list %}
    <ul>
    {% for artist in artist_list %}
        <li><a href="/history/{{artist.id}}/">{{ artist.artist_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No artist are available.</p>
{% endif %}
    <form method="post" action="{% url 'history:newArtist' %}">
      {% csrf_token %}
      <label for="newArtist">New Artist</label><br>
      <input type="text" name="artist" id = "newArtist">
      <input type = "submit" value="Artist">
    </form>